### ISSUE TITLE
Crash with "unexpected EOF" if org's name or letter's case is not correct

### ISSUE THREAD

**Issue by mauricemensing** [terraform-providers/terraform-provider-vcd#120]
Hello Guys,

when im trying to run terraform apply for the vcd Provider https://github.com/lvirbalas/terraform-provider-vcd/tree/vmware-takes-ownership terraform crashes. I compile this provider with go and terraform init accept it as a normal provider. Terraform plan works as normal.

### Terraform Version

Terraform v0.11.10

### Terraform Configuration Files
All variables are filled in extern file.
```hcl
provider "vcd" {
  user                 = "${var.vcd_user}"
  password             = "${var.vcd_pass}"
  org                  = "${var.vcd_org}"
  url                  = "${var.vcd_url}"
  vdc                  = "${var.vcd_vdc}"
  max_retry_timeout    = "${var.vcd_max_retry_timeout}"
  allow_unverified_ssl = "${var.vcd_allow_unverified_ssl}"

}
resource "vcd_network_routed" "net00" {
	name = "${var.vcdnet_name}"
	edge_gateway = "${var.vcdnet_edge_gateway}"
	gateway = "${var.vcdnet_gateway}"
	
		static_ip_pool {
		start_address = "${var.vcdnet_static_ip_pool_start}"
		end_address = "${var.vcdnet_static_ip_pool_end}"
	}
}
resource "vcd_vapp" "mmig_vapp" {	

	name = "${var.vcd_vapp_name}"
	power_on = false 
	network_name = "${var.vcdnet_name}"

}

resource "vcd_vapp_vm" "my_vm01" {
	vapp_name = "mmig-vcloud-providers-testspace"
	network_name = "${var.vcdnet_name}"
	power_on = false
	name = "${var.vmnamewin}"
	catalog_name = "${var.catalognamewin}"
	template_name = "${var.templatenamewin}"
	memory = 4096
	cpus = 2
	ip = ""
	initscript = "${var.vcd_vapp_vm_vm01_initscript}"
}
```

### Debug Output

https://gist.github.com/mauricemensing/99a7a1bfccc37b2584932595e5de6d62
https://gist.github.com/mauricemensing/057ef3439b3c108dc71d2f1aa57d4f7d
### Panic Output
panic: runtime error: invalid memory address or nil pointer dereference

### Expected Behavior
What should have happened?
Create Network, vapp and vm in vCloud director with the vcd Provider from @lvirbalas 

### Actual Behavior
What actually happened?
Terraform crashes with this error "panic: runtime error: invalid memory address or nil pointer dereference"

### Steps to Reproduce
Windows:
Please list the steps required to reproduce the issue, for example:
1. terraform init --plugin-dir=%APPDATA%/terraform.d/plugins/windows_amd64/
2. `terraform apply`

Linux: 
1. terraform init 
2. terraform apply

**Comment by mauricemensing** [comment]
Update: Similar Error when deploying the same Terraform script at our linux machine 
https://gist.github.com/mauricemensing/057ef3439b3c108dc71d2f1aa57d4f7d

**Comment by vbauzysvmware** [comment]
Could you use:
`export GOVCD_LOG=1` and this
will enable logs for the VCD library, and by default it creates a file named go-vcloud-director.log with all the API requests and responses. Sharing this log will help much.

**Comment by mauricemensing** [comment]
https://gist.github.com/mauricemensing/c68b635bc31332bcd61ef2e0b87e4458 @vbauzysvmware  thanks a lot

**Comment by vbauzysvmware** [comment]
Hi @mauricemensing with info I have at hand I recommend to check your organization name you using. Vcd returns only one organization which name you can found in 4479 line of your logs and seems it didn't match with your provided in terraform configuration.
BTW I run terraform script in my env and it is working.

**Comment by mauricemensing** [comment]
Thank you! There was the issue.  In the Master Branch i didn't need capital letters, now i need them.

**Comment by vbauzysvmware** [comment]
you mean that organization name could be lowercase?:)
Anyways, I identify option how to improve code to be more explicit on such case.

**Comment by lvirbalas** [comment]
@vbauzysvmware if you could add a more sensible error message for this case it would be very helpful.

**Comment by lvirbalas** [comment]
I confirm the crash happens if you just change one letter's case in provider's `org` argument. I'll change the name of this issue to reflect this. @vbauzysvmware when you look at this issue, please adjust so the org is case insensitive.

```
Error: Error applying plan:

1 error(s) occurred:

* vcd_catalog.TerraformCatalog: 1 error(s) occurred:

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
* vcd_catalog.TerraformCatalog: unexpected EOF


Terraform does not automatically rollback in the face of errors.
Terraform crashed! This is always indicative of a bug within Terraform.
Instead, your Terraform state file has been partially updated with
A crash log has been placed at "crash.log" relative to your current
any resources that successfully completed. Please address the error
working directory. It would be immensely helpful if you could please
above and apply again to incrementally change your infrastructure.report the crash with Terraform[1] so that we can fix this.



When reporting bugs, please include your terraform version. That

information is available on the first line of crash.log. You can also
panic: runtime error: invalid memory address or nil pointer dereference
get it by running 'terraform --version' on the command line.

2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x158dd8c]
[1]: https://github.com/hashicorp/terraform/issues
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: 

2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: goroutine 69 [running]:
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/vmware/go-vcloud-director/govcd.(*AdminOrg).CreateCatalog(0xc4205dd980, 0xc42035a290, 0x10, 0xc42035a2a0, 0xc, 0x0, 0x1735d00, 0xc4200c76d8, 0xc4200c76e0)
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: 	/Users/lvirbalas/go/src/github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/vmware/go-vcloud-director/govcd/org.go:179 +0xdc
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: github.com/terraform-providers/terraform-provider-vcd/vcd.resourceVcdCatalogCreate(0xc42024c3f0, 0x17164c0, 0xc4203ba280, 0x24, 0x1bb3880)
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: 	/Users/lvirbalas/go/src/github.com/terraform-providers/terraform-provider-vcd/vcd/resource_vcd_catalog.go:64 +0x20c
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420428780, 0xc4200d0410, 0xc4203185a0, 0x17164c0, 0xc4203ba280, 0xc420178b01, 0xc420067b88, 0x10ba5ac)
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: 	/Users/lvirbalas/go/src/github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:193 +0x372
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4201e17a0, 0xc4200d0280, 0xc4200d0410, 0xc4203185a0, 0x18, 0x18, 0xc4203185e0)
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: 	/Users/lvirbalas/go/src/github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:259 +0xa4
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc42036e1c0, 0xc420318180, 0xc420346420, 0x0, 0x0)
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: 	/Users/lvirbalas/go/src/github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: reflect.Value.call(0xc420148420, 0xc4200ce4f8, 0x13, 0x1758dd7, 0x4, 0xc420067f18, 0x3, 0x3, 0xc4200c7e40, 0x0, ...)
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: 	/usr/local/go/src/reflect/value.go:447 +0x969
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: reflect.Value.Call(0xc420148420, 0xc4200ce4f8, 0x13, 0xc420051718, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: 	/usr/local/go/src/reflect/value.go:308 +0xa4
2018-12-06T18:06:53.613+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: net/rpc.(*service).call(0xc420072540, 0xc4203ba190, 0xc4200741c8, 0xc4200741e0, 0xc42032e080, 0xc420070720, 0x1625040, 0xc420318180, 0x16, 0x1625080, ...)
2018-12-06T18:06:53.614+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
2018-12-06T18:06:53.614+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: created by net/rpc.(*Server).ServeCodec
2018-12-06T18:06:53.614+0700 [DEBUG] plugin.terraform-provider-vcd_v2.0.0: 	/usr/local/go/src/net/rpc/server.go:480 +0x43a
2018/12/06 18:06:53 [TRACE] root: eval: *terraform.EvalWriteState
2018/12/06 18:06:53 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/12/06 18:06:53 [TRACE] root: eval: *terraform.EvalIf
2018/12/06 18:06:53 [TRACE] root: eval: *terraform.EvalWriteState
2018/12/06 18:06:53 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/12/06 18:06:53 [TRACE] root: eval: *terraform.EvalApplyPost
2018/12/06 18:06:53 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vcd_catalog.TerraformCatalog: unexpected EOF
2018/12/06 18:06:53 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vcd_catalog.TerraformCatalog: unexpected EOF
2018/12/06 18:06:53 [TRACE] [walkApply] Exiting eval tree: vcd_catalog.TerraformCatalog
2018/12/06 18:06:53 [TRACE] dag/walk: upstream errored, not walking "vcd_catalog_item.yVM"
2018/12/06 18:06:53 [TRACE] dag/walk: upstream errored, not walking "provider.vcd (close)"
2018/12/06 18:06:53 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/12/06 18:06:53 [TRACE] dag/walk: upstream errored, not walking "root"
2018-12-06T18:06:53.616+0700 [DEBUG] plugin: plugin process exited: path=/Users/lvirbalas/.terraform.d/plugins/terraform-provider-vcd_v2.0.0
2018/12/06 18:06:53 [TRACE] Preserving existing state lineage "5a11a7e9-e3be-3438-0a6c-eaf5d93583cd"
2018/12/06 18:06:53 [TRACE] Preserving existing state lineage "5a11a7e9-e3be-3438-0a6c-eaf5d93583cd"
2018/12/06 18:06:53 [TRACE] Preserving existing state lineage "5a11a7e9-e3be-3438-0a6c-eaf5d93583cd"
2018/12/06 18:06:53 [TRACE] Preserving existing state lineage "5a11a7e9-e3be-3438-0a6c-eaf5d93583cd"
2018/12/06 18:06:53 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-12-06T18:06:53.624+0700 [WARN ] plugin: error closing client during Kill: err="connection is shut down"


Process finished with exit code 1
```

**Comment by vbauzysvmware** [comment]
Now shows explicitly error when organization isn't found.

**Comment by pjamelot** [comment]
Hello, I think the problem is due to the catalog because it is not a public catalog.
How do you set a the catalog_name parameter when it is a catalog  from the vorg?
BR,
