### ISSUE TITLE
Unable to create vapp_vm that attaches to predefined org VDC Network

### ISSUE THREAD

**Issue by yRIjom** [terraform-providers/terraform-provider-vcd#213]
### Terraform Version
Terraform v0.11.11
+ provider.vcd v2.0.0

### vCloud Directory Version
8.20

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
variable username {}
variable password {}
variable org {
  default = "TEST"
}
variable vdc {
  default = "TEST_VDC"
}
variable url {
  default = "https://192.168.1.100/api"
}
variable allow_unverified_ssl {
  default = "true"
}

variable vapp_name {
  default = "STORAGE"
}

variable catalog_name {
  default = "TEST_CATALOG"
}
variable template_name {
  default = "rhel7-template"
}

provider "vcd" {
  user = "${var.username}"
  password = "${var.password}"
  org = "${var.org}"
  vdc = "${var.vdc}"
  url = "${var.url}"
  allow_unverified_ssl = "${var.allow_unverified_ssl}"
}

resource "vcd_vapp_vm" "gluster1" {
  vapp_name = "${var.vapp_name}"
  name = "gluster1"
  catalog_name = "${var.catalog_name}"
  template_name = "${var.template_name}"
  network_name = "SUBNET41"
  ip = "allocated"
}


```

### Panic Output

```
2019-03-25T12:59:28.322-0400 [DEBUG] plugin.terraform-provider-vcd_v2.0.0_x4: 2019/03/25 12:59:28 [TRACE] Network name found: SUBNET41
2019-03-25T12:59:28.322-0400 [DEBUG] plugin.terraform-provider-vcd_v2.0.0_x4: 2019/03/25 12:59:28 [DEBUG] Waiting for state to become: success
2019-03-25T12:59:28.322-0400 [DEBUG] plugin.terraform-provider-vcd_v2.0.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2019-03-25T12:59:28.322-0400 [DEBUG] plugin.terraform-provider-vcd_v2.0.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x9d7bc5]
2019-03-25T12:59:28.322-0400 [DEBUG] plugin.terraform-provider-vcd_v2.0.0_x4:
2019-03-25T12:59:28.322-0400 [DEBUG] plugin.terraform-provider-vcd_v2.0.0_x4: goroutine 45 [running]:
2019-03-25T12:59:28.322-0400 [DEBUG] plugin.terraform-provider-vcd_v2.0.0_x4: github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/vmware/go-vcloud-director/govcd.(*VApp).AddVM(0xc000155f20, 0xc00000c238, 0x1, 0x1, 0xc000428120, 0xc000178000, 0xc000285310, 0x8, 0x1, 0x0, ...)
2019-03-25T12:59:28.322-0400 [DEBUG] plugin.terraform-provider-vcd_v2.0.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/vmware/go-vcloud-director/govcd/vapp.go:113 +0x335
2019-03-25T12:59:28.322-0400 [DEBUG] plugin.terraform-provider-vcd_v2.0.0_x4: github.com/terraform-providers/terraform-provider-vcd/vcd.resourceVcdVAppVmCreate.func(0xc000323c20)
2019-03-25T12:59:28.322-0400 [DEBUG] plugin.terraform-provider-vcd_v2.0.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vcd/resource_vcd_vapp_vm.go:185 +0x1e1
```

### Expected Behavior

A VM should have been created in the STORAGE vApp and should have featured a NIC that was connected to the SUBNET41 network. 

### Actual Behavior

No VM is created and terraform crashes.

### Steps to Reproduce
1. Use the vCloud Director UI to create a organization VDC network named "SUBNET41". This network should have a static pool of IP addresses assigned to it.
2. Use the vCloud Director UI to create a vApp template that features 1 NIC.
3. Create infra.tf, using the above configuration file
4. `terraform init`
5. `terraform apply -auto-approve`

**Comment by yRIjom** [comment]
I realized this is because the template that I'm using had no network interface card present. This means that this ticket is a duplicate of #26 .

I added a network interface to the template and was able to provision the VM as an organization admin.

**Comment by Didainius** [comment]
@yRIjom, I was trying to replicate to get the panic, but couldn't.

Here's what I've tried on ( vCD 8.20.0 and vCD 9.5) on provider version 2.0 and 2.1:
* Created a org-vdc network SUBNET41
* Uploaded a VM template without network interface.
* Created a vApp and setup `SUBNET41` in it's networking.
* Tried to add VM to vApp  with:
```hcl
resource "vcd_vapp_vm" "gluster1" {
  vapp_name = "STORAGE"
  name = "gluster1"
  catalog_name = "my-catalog"
  template_name = "vm-no-nic"
  network_name = "SUBNET41"
  ip = "allocated"
}
```
And it always worked.

Do you have any additional information so that I could reproduce it?

**Comment by Didainius** [comment]
Closing it. @yRIjom, feel free to reopen if you have any news.
